Repository canonical-web-and-design/build.snapcraft.io, pull requests merged in 2018-06, with the labels that each got.

#1112 Add configuration for public sentry dsn var
  charm/config.yaml
  charm/reactive/snap-build.py
  charm/templates/snap-build-poller_secrets.j2
  charm/templates/snap-build_systemd.j2
Labels: Review: Code +1

#1113 Use public sentry DSN for front-end error reporting
  src/server/helpers/html.js
Labels: Review: Code +1

#1114 Add some logging around association handle storing in session
  src/server/openid/relyingparty.js
Labels: Review: Code +1

#1111 Only store one token per session
  src/server/handlers/universal.js
  src/server/middleware/csrf-token.js
  test/routes/src/server/routes/t_github.js
  test/routes/src/server/routes/t_launchpad.js
Labels: Review: Code +1, Review: QA +1

#1118 Fail early on expired session
  src/common/components/repositories-home/index.js
  src/server/handlers/launchpad.js
Labels: Review: Code +1, Review: QA +1

#1119 Update badge cache headers as per GH expects it
  src/server/handlers/badge.js
Labels: Review: Code +1, Review: QA +1

#1120 Fix snaps API request credentials to make sure session cookie is sent
  src/common/actions/snap-builds.js
Labels: Priority: Critical

#1122 Make sure to request builds of repos that were never built
  src/common/components/repositories-home/index.js
Labels: Review: Code +1, Review: QA +1
